config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  get 'shopping_lists/show'
  devise_for :users
  root 'foods#index'
  get 'users/index'
  get 'users/sign_out'
  resources :users, only: %i[index]
  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    resources :shopping_list, only: [:index ,:show]
  end
  resources :inventories do
    resources :inventory_foods
  end
  put 'recipes/:id/update', to: 'recipes#update', as: 'update'
  post 'shopping_list/recipe_id=:recipe_id', to: 'recipes#generate_list', as: 'generate_shopping_list'
  get 'public_recipes', to: 'recipes#public', as: 'public'
  get 'shopping_list/recipe_id=:recipe_id&inventory_id=:inventory_id', to: 'recipes#generate', as: "shopping_list"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods
  validates :name, presence: true
  validates :description, presence: true, length: { maximum: 250 }
  # validates :cookingTime, :preparationTime, numericality: { greater_than_or_equal_to: 0 }
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:notice] = 'Recipe successfully created'
    else
      flash[:notice] = 'An error occured, please try again'
      render 'new'
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(public: params[:public])
      flash[:success] = 'Recipe was successfully updated'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to recipe_path(@recipe)
  end

  def public
    @recipes = Recipe.where(public: true)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = 'Recipe Deleted'
    redirect_to recipes_url
  end

  def generate_list
    redirect_to shopping_list_path(params[:recipe_id])
  end

  def generate
    @quantity = []
    @foods = []
    @recipe_food = RecipeFood.where(recipe_id: params[:recipe_id])
    @recipe_food.each do |recipe_food|
      found = false
      check_recipe_food = Food.find(recipe_food.food_id)
      next if found

      @quantity << [recipe_food.quantity, check_recipe_food.price]
      @foods << check_recipe_food.name
    end
    @total = 0
    @quantity.each do |q|
      @total += q[0] * q[1]
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :cooking_time, :preparation_time, :description)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_generatepopup.html.erb
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  Generate Shopping List
</button>
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="d-flex flex-column p-2">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_recipe_form.html.erb
<%= form_with(model: recipe, url: recipes_path) do |form|%>
  <%= form.text_field :name, placeholder: 'Name', id:"name", class:"form-control" %>
  <br>
  <%= form.text_field :cookingTime, placeholder: 'Cooking time', id:"cookingTime", class:"form-control" %>
  <br>
  <%= form.text_field :preparationTime, placeholder: 'Preparation time', id:"preparationTime",class:"form-control" %>
  <br>
  <%= form.text_area :description, placeholder: 'Description', id:"description", class:"form-control" %>
  <br>
  <div class="actions">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<main class="recipes-container">
  <div class="create-div">
    <%= link_to "Create New Recipe", new_recipe_path, class: "btn btn-success"%>
  </div>
  <div class='recipe_holder'>
    <% @recipes.each do |recipe|%>
      <div class="recipe">
        <div class="recipe-name">
          <div>
            <%= link_to "#{recipe.name}", recipe_path(recipe), id: "recipe_#{recipe.id}", class: "text-reset text-decoration-none fs-3 text-capitalize" %>
          </div>
          <div class="remove-recipe">
            <%= button_to 'Remove Recipe', recipe_path(recipe), method: :delete, class: "btn btn-success" %>
          </div>
        </div>
        <div class="description">
          <p><%= recipe.description %></p>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/recipes/new.html.erb
<main class="recipes-container">
  <h1>New Recipe</h1>
  <p>Add your recipe:</p>
  <%= render 'recipe_form', recipe: @recipe %>
  <%= link_to 'Cancel', recipes_path, class:'cancel-button' %>
</main>

app/views/recipes/public.html.erb
<section>
  <h3 class="fs-1 lh-lg fw-semibold mt-5 text-center">Public Recipes</h3>
  <div class="public-c">
    <ul class="m-0 p-0">
      <% @recipes.each do |recipe| %>
        <li class="card list-style-none mb-3">
          <div class="card-header fs-4">
            <%= link_to recipe[:name], recipe_path(id: recipe[:id]) %>
          </div>
          <div class="card-body">
            <h5 class="card-title">By: <%=recipe.user.name%></h5>
            <div class="d-flex flex-column float-end ">
              <p>Total food items: <%= recipe.cookingTime %></p>
              <p>Total price: <%= recipe.preparationTime %></p>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</section>

app/views/recipes/show.html.erb
<% if can? :read , @recipe %>
  <div class="recipe-detail">
    <h1><%= @recipe.name %></h1>
    <div>
      <div class="detals">
        <div class="info">
          <div class="time">
            <p class="fs-4">Preparation time:  </p><span class="fs-4"><%=@recipe.preparationTime%></span>
          </div>
          <div class="time">
            <p class="fs-4">Cooking time:  </p><span class="fs-4"><%=@recipe.cookingTime%></span>
          </div>
        </div>
        <% if can? :update, @recipe%>
          <div class="status">
            <%= form_with url: update_path(@recipe), method: "put" do |form| %>
              <div class="form-check form-switch">
                <% if @recipe.public == false %>
                  <%= form.check_box :public, class:"form-check-input fs-4", id:"flexSwitchCheckDefault", onchange: "this.form.submit();"%>
                  <label class="form-check-label fs-4" for="flexSwitchCheckDefault">Public</label>
                <% else %>
                  <%= form.check_box :public, class:"form-check-input fs-4", id:"flexSwitchCheckChecked", checked: true, onchange: "this.form.submit();" %>
                  <label class="form-check-label fs-4" for="flexSwitchCheckChecked">Public</label>
                <%end%>
              </div>
            <%end%>
          </div>
        <%end%>
      </div>
      <div>
        <div class="bg-light mb-3">
          <p class="fs-5"><%=@recipe.description%></p>
        </div>
      </div>
      <div class="actions">
        <div class="gen-shopping-list">
          <%= link_to 'Generate shopping list', recipe_shopping_list_path(@recipe.id), class: 'btn btn-outline-success' %>
        </div>
        <% if can? :update, @recipe%>
          <div class="add-ingredient">
            <%= link_to 'Add ingredient', new_recipe_recipe_food_path(@recipe), class: 'btn btn-outline-success' %>
          </div>
        <%end%>
      </div>
      <hr>
    </div>


    <table class="table table-striped table-bordered">
      <% if @recipe.recipe_foods.any? %>
        <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Action</th>
        </tr>
        </thead>

        <tbody>
        <% @recipe.recipe_foods.each do |fd|%>
          <tr>
            <td><%= fd.food.name%></th>
            <td><%= fd.quantity%><%= fd.food.measurementUnit  %></td>
            <td>$<%= fd.quantity* fd.food.price %></td>
            <td class="mb-3 col-sm-3">
              <% if can? :destroy, @recipe %>

                <%=button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: fd.id), method: :delete, class:"btn btn-outline-dark"%>
                <%=link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: fd.id), class:"btn btn-outline-dark"%>
              <%end%>
            </td>
          </tr>

          </tbody>
        <%end%>
      <%end%>
    </table>
  </div>
<%end%>