config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  get 'shopping_lists/show'
  devise_for :users
  root 'foods#index'
  get 'users/index'
  get 'users/sign_out'
  resources :users, only: %i[index]
  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    resources :shopping_list, only: [:index ,:show]
  end
  resources :inventories do
    resources :inventory_foods
  end
  put 'recipes/:id/update', to: 'recipes#update', as: 'update'
  post 'shopping_list/recipe_id=:recipe_id', to: 'recipes#generate_list', as: 'generate_shopping_list'
  get 'public_recipes', to: 'recipes#public', as: 'public'
  get 'shopping_list/recipe_id=:recipe_id&inventory_id=:inventory_id', to: 'recipes#generate', as: "shopping_list"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3 }
  validates :measurementUnit, presence: true
  validates :price, numericality: { greater_than: 0, less_than: 1_000_000 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      flash[:notice] = 'Food created successfully.'
      redirect_to foods_path
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    authorize! :destroy, @food
    @food.destroy
    flash[:success] = 'Food is removed successfully'
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurementUnit, :price, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<h1 class="heading"> All Foods</h1>

<div class="mb-3 col-sm-2 btn-div">
  <%= link_to "Add food", new_food_path, class:"btn btn-primary form-control" %>
</div>

<div class="listDiv">
  <table class="table table-striped table-bordered">
    <thead>
    <tr>
      <th>Food</th>
      <th>Measurement_Unit</th>
      <th>Unit Price</th>
      <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <% @foods.each do |food|%>
      <tr>
        <td><%= food.name%></th>
        <td><%= food.measurementUnit%></td>
        <td>$<%= food.price%></td>
        <td class="mb-3 col-sm-2">
          <%if can? :destroy, food%>
            <%= button_to "Delete Food", food_path(food.id), method: :delete, data: {confirm: "Are you sure"}, :class => "btn btn-sm btn-danger"%>      </td>
          <%end%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>

app/views/foods/new.html.erb
<h2 class="heading">Add Food</h2>
<div>
  <%= form_with  model: @food, class:"input-form"  do |f|%>
    <div class="form-div" >
      <%= f.hidden_field :user_id, value: @user.id %>

      <div class="mb-3 col-sm-8">
        <%= f.label :name, class:"form-label" %><br>
        <%= f.text_field :name, class:"form-control",  required: true, id:"name"%><br>
      </div>

      <div class="mb-3 col-sm-8">
        <%= f.label :measurementUnit, class:"form-label" %><br>
        <%= f.text_field :measurementUnit,  class:"form-control" , required: true, id:"measurement"%><br>
      </div>

      <div class="mb-3 col-sm-8">
        <%= f.label :price, class:"form-label" %><br>
        <%= f.number_field :price ,  class:"form-control" , required: true, id:"price", step: :any%><br>
      </div>

      <div class="mb-3 col-sm-2">
        <%= f.submit "Create Food", class:"btn btn-primary form-control" %>
      </div>
    </div>
  <%end%>
  <div class="form-div" >
    <div class="mb-3 col-sm-2">

      <%=link_to 'Back', foods_path, class:"btn btn-primary form-control"%>
    </div>
  </div>
</div>