config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  get 'shopping_lists/show'
  devise_for :users
  root 'foods#index'
  get 'users/index'
  get 'users/sign_out'
  resources :users, only: %i[index]
  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    resources :shopping_list, only: [:index ,:show]
  end
  resources :inventories do
    resources :inventory_foods
  end
  put 'recipes/:id/update', to: 'recipes#update', as: 'update'
  post 'shopping_list/recipe_id=:recipe_id', to: 'recipes#generate_list', as: 'generate_shopping_list'
  get 'public_recipes', to: 'recipes#public', as: 'public'
  get 'shopping_list/recipe_id=:recipe_id&inventory_id=:inventory_id', to: 'recipes#generate', as: "shopping_list"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  # validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 1_000_000 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @ingredient_count = 0
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_foods_params)
    if @recipe_food.save
      flash[:notice] = 'Food Created Successfully'
      @ingredient_count += 1
    else
      render :new
    end
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(update_params)
      flash[:success] = 'Updated Recipe Food Successfully'
    else
      redirect_to recipe_path(@recipe_food.recipe_id)
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Foods Removed'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  private

  def update_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end

  def recipe_foods_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/create.html.erb
<h1>RecipeFoods#create</h1>
<p>Find me in app/views/recipe_foods/create.html.erb</p>

app/views/recipe_foods/destroy.html.erb
<h1>RecipeFoods#destroy</h1>
<p>Find me in app/views/recipe_foods/destroy.html.erb</p>

app/views/recipe_foods/edit.html.erb
<div>
  <%= form_with  model: @recipe_food, url: { action: "update"}, local: true do |form|%>
    <div>
      <div>
        <%= form.label :food %><br>
        <%= form.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} %><br>
      </div>

      <div>
        <%= form.label :quantity %><br>
        <%= form.number_field :quantity, required: true, min:1%><br>
      </div>

      <div>
        <%= form.submit "Update Foods of the Recipe" %>
      </div>
    </div>
  <%end%>
  <div>
    <div>
      <%=link_to 'Cancel', recipes_path %>
    </div>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<h2 class="heading">Add Recipe Food</h2>
<div>
  <%= form_with  model: [@recipe, @recipe.recipe_foods.create], class:"input-form"  do |f|%>
    <div class="form-div" >

      <div class="mb-3 col-sm-8">
        <%= f.label :food, class:"form-label" %><br>
        <%= f.select :food_id, current_user.foods.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>

      </div>

      <div class="mb-3 col-sm-8">
        <%= f.label :quantity, class:"form-label" %><br>
        <%= f.number_field :quantity ,  class:"form-control" , required: true, placeholder: '1',  min: 1%><br>
      </div>

      <div class="mb-3 col-sm-2">
        <%= f.submit "Create Recipe_Food", class:"btn btn-success form-control" %>
      </div>
    </div>
  <% end %>
  <div class="form-div" >
    <div class="mb-3 col-sm-2">

      <%=link_to 'Back', foods_path, class:"btn btn-success form-control"%>
    </div>
  </div>
</div>

app/views/recipe_foods/update.html.erb
<h1>RecipeFoods#update</h1>
<p>Find me in app/views/recipe_foods/update.html.erb</p>